
package enumeraciones;

public enum Dias {
    //BUENA PRACTICA PONER EN LOS ENUM TODAS LAS LETRAS EN MAYUSCULAS
    //LOS VALORES SON STATICOS Y FINALES POR LO QUE NO PODEMOS MODIFICARLOS PERO PODEMOS ACCEDER A ELLOS DE MANERA DIRECTA 
    DOMINGO,
    LUNES,
    MARTES,
    MIERCOLES,
    JUEVES,
    VIERNES,
    SABADO
}
